config/routes.rb
Demo::Application.routes.draw do

	resources :events

	root :to => "welcome#index"	
	get "welcome/say_hello" => "welcome#say"

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :find_event, :only => [:show, :edit, :update, :destroy]	

	def index
		@events = Event.page(params[:page]).per(5)

		respond_to do |format|
			format.html
			format.xml { render :xml => @events.to_xml }
			format.json { render :json => @events.to_json }
			format.atom { @feed_title = "My event list"}
		end
	end

	def show
		@page_title = @event.name
	end

	def new
		@event = Event.new	
	end

	def create
		@event = Event.new(params[:event])
		flash[:notice] = "event was successfully created"
		if @event.save
			redirect_to events_url
		else
			render :action => :new
		end
	end

	def edit
	end

	def update
		flash[:notice] = "event was successfully updated"
		if @event.update_attributes(params[:event])
			redirect_to event_url(@event)
		else
			render :action =>  :edit
		end
	end

	def destroy
		@event.destroy
		flash[:alert] = "event was successfully deleted"

		redirect_to events_url
	end

	protected
	
	def find_event
		@event = Event.find(params[:id])
	end









end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def say
		
	end

	def index 
	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
	<%= f.label :name, "Name"%>
	<%= f.text_field :name %>

	<%= f.label :description, "Description"%>
	<%= f.text_area :description %>

	<% if @event.errors.any?%>
		<ul>
			<% @event.errors.full_messages.each do |msg|%>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :put  do |f| %>
	<%= render :partial => 'form', :locals => { :f => f }%>
	<%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<ul>
<% @events.each do |event|%>
	<li>
		<h3><%= link_to event.name, event_path(event)%></h3>
		<%= link_to 'Edit', edit_event_path(event)%>
		<%= button_to 'Delete', event_path(event), :method => :delete %>
	</li>
<% end %>
</ul>

<%= paginate @events %>

<%= link_to 'New event', new_event_path %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application"%></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p>Hola! It's<%= Time.now%></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello World!</h1>
<p><%= link_to "Home", root_path %></p>